/* do not edit this file - it is machine generated */
#include <jni.h>
/* header for class org_moorecoin_nativesecp256k1 */

#ifndef _included_org_moorecoin_nativesecp256k1
#define _included_org_moorecoin_nativesecp256k1
#ifdef __cplusplus
extern "c" {
#endif
/*
 * class:     org_moorecoin_nativesecp256k1
 * method:    secp256k1_ecdsa_verify
 * signature: (ljava/nio/bytebuffer;)i
 */
jniexport jint jnicall java_org_moorecoin_nativesecp256k1_secp256k1_1ecdsa_1verify
  (jnienv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
