// tinyformat.h
// copyright (c) 2011, chris foster [chris42f (at) gmail (d0t) com]
//
// boost software license - version 1.0
//
// permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "software") to use, reproduce, display, distribute,
// execute, and transmit the software, and to prepare derivative works of the
// software, and to permit third-parties to whom the software is furnished to
// do so, all subject to the following:
//
// the copyright notices in the software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the software, in whole or in part, and
// all derivative works of the software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// the software is provided "as is", without warranty of any kind, express or
// implied, including but not limited to the warranties of merchantability,
// fitness for a particular purpose, title and non-infringement. in no event
// shall the copyright holders or anyone distributing the software be liable
// for any damages or other liability, whether in contract, tort or otherwise,
// arising from, out of or in connection with the software or the use or other
// dealings in the software.

//------------------------------------------------------------------------------
// tinyformat: a minimal type safe printf replacement
//
// tinyformat.h is a type safe printf replacement library in a single c++
// header file.  design goals include:
//
// * type safety and extensibility for user defined types.
// * c99 printf() compatibility, to the extent possible using std::ostream
// * simplicity and minimalism.  a single header file to include and distribute
//   with your projects.
// * augment rather than replace the standard stream formatting mechanism
// * c++98 support, with optional c++11 niceties
//
//
// main interface example usage
// ----------------------------
//
// to print a date to std::cout:
//
//   std::string weekday = "wednesday";
//   const char* month = "july";
//   size_t day = 27;
//   long hour = 14;
//   int min = 44;
//
//   tfm::printf("%s, %s %d, %.2d:%.2d\n", weekday, month, day, hour, min);
//
// the strange types here emphasize the type safety of the interface; it is
// possible to print a std::string using the "%s" conversion, and a
// size_t using the "%d" conversion.  a similar result could be achieved
// using either of the tfm::format() functions.  one prints on a user provided
// stream:
//
//   tfm::format(std::cerr, "%s, %s %d, %.2d:%.2d\n",
//               weekday, month, day, hour, min);
//
// the other returns a std::string:
//
//   std::string date = tfm::format("%s, %s %d, %.2d:%.2d\n",
//                                  weekday, month, day, hour, min);
//   std::cout << date;
//
// these are the three primary interface functions.
//
//
// user defined format functions
// -----------------------------
//
// simulating variadic templates in c++98 is pretty painful since it requires
// writing out the same function for each desired number of arguments.  to make
// this bearable tinyformat comes with a set of macros which are used
// internally to generate the api, but which may also be used in user code.
//
// the three macros tinyformat_argtypes(n), tinyformat_varargs(n) and
// tinyformat_passargs(n) will generate a list of n argument types,
// type/name pairs and argument names respectively when called with an integer
// n between 1 and 16.  we can use these to define a macro which generates the
// desired user defined function with n arguments.  to generate all 16 user
// defined function bodies, use the macro tinyformat_foreach_argnum.  for an
// example, see the implementation of printf() at the end of the source file.
//
//
// additional api information
// --------------------------
//
// error handling: define tinyformat_error to customize the error handling for
// format strings which are unsupported or have the wrong number of format
// specifiers (calls assert() by default).
//
// user defined types: uses operator<< for user defined types by default.
// overload formatvalue() for more control.


#ifndef tinyformat_h_included
#define tinyformat_h_included

namespace tinyformat {}
//------------------------------------------------------------------------------
// config section.  customize to your liking!

// namespace alias to encourage brevity
namespace tfm = tinyformat;

// error handling; calls assert() by default.
#define tinyformat_error(reasonstring) throw std::runtime_error(reasonstring)

// define for c++11 variadic templates which make the code shorter & more
// general.  if you don't define this, c++11 support is autodetected below.
// #define tinyformat_use_variadic_templates


//------------------------------------------------------------------------------
// implementation details.
#include <cassert>
#include <iostream>
#include <sstream>
#include <stdexcept>

#ifndef tinyformat_error
#   define tinyformat_error(reason) assert(0 && reason)
#endif

#if !defined(tinyformat_use_variadic_templates) && !defined(tinyformat_no_variadic_templates)
#   ifdef __gxx_experimental_cxx0x__
#       define tinyformat_use_variadic_templates
#   endif
#endif

#ifdef __gnuc__
#   define tinyformat_noinline __attribute__((noinline))
#elif defined(_msc_ver)
#   define tinyformat_noinline __declspec(noinline)
#else
#   define tinyformat_noinline
#endif

#if defined(__glibcxx__) && __glibcxx__ < 20080201
//  std::showpos is broken on old libstdc++ as provided with osx.  see
//  http://gcc.gnu.org/ml/libstdc++/2007-11/msg00075.html
#   define tinyformat_old_libstdcplusplus_workaround
#endif

namespace tinyformat {

//------------------------------------------------------------------------------
namespace detail {

// test whether type t1 is convertible to type t2
template <typename t1, typename t2>
struct is_convertible
{
    private:
        // two types of different size
        struct fail { char dummy[2]; };
        struct succeed { char dummy; };
        // try to convert a t1 to a t2 by plugging into tryconvert
        static fail tryconvert(...);
        static succeed tryconvert(const t2&);
        static const t1& maket1();
    public:
#       ifdef _msc_ver
        // disable spurious loss of precision warnings in tryconvert(maket1())
#       pragma warning(push)
#       pragma warning(disable:4244)
#       pragma warning(disable:4267)
#       endif
        // standard trick: the (...) version of tryconvert will be chosen from
        // the overload set only if the version taking a t2 doesn't match.
        // then we compare the sizes of the return types to check which
        // function matched.  very neat, in a disgusting kind of way :)
        static const bool value =
            sizeof(tryconvert(maket1())) == sizeof(succeed);
#       ifdef _msc_ver
#       pragma warning(pop)
#       endif
};


// detect when a type is not a wchar_t string
template<typename t> struct is_wchar { typedef int tinyformat_wchar_is_not_supported; };
template<> struct is_wchar<wchar_t*> {};
template<> struct is_wchar<const wchar_t*> {};
template<int n> struct is_wchar<const wchar_t[n]> {};
template<int n> struct is_wchar<wchar_t[n]> {};


// format the value by casting to type fmtt.  this default implementation
// should never be called.
template<typename t, typename fmtt, bool convertible = is_convertible<t, fmtt>::value>
struct formatvalueastype
{
    static void invoke(std::ostream& /*out*/, const t& /*value*/) { assert(0); }
};
// specialized version for types that can actually be converted to fmtt, as
// indicated by the "convertible" template parameter.
template<typename t, typename fmtt>
struct formatvalueastype<t,fmtt,true>
{
    static void invoke(std::ostream& out, const t& value)
        { out << static_cast<fmtt>(value); }
};

#ifdef tinyformat_old_libstdcplusplus_workaround
template<typename t, bool convertible = is_convertible<t, int>::value>
struct formatzerointegerworkaround
{
    static bool invoke(std::ostream& /**/, const t& /**/) { return false; }
};
template<typename t>
struct formatzerointegerworkaround<t,true>
{
    static bool invoke(std::ostream& out, const t& value)
    {
        if (static_cast<int>(value) == 0 && out.flags() & std::ios::showpos)
        {
            out << "+0";
            return true;
        }
        return false;
    }
};
#endif // tinyformat_old_libstdcplusplus_workaround

// convert an arbitrary type to integer.  the version with convertible=false
// throws an error.
template<typename t, bool convertible = is_convertible<t,int>::value>
struct converttoint
{
    static int invoke(const t& /*value*/)
    {
        tinyformat_error("tinyformat: cannot convert from argument type to "
                         "integer for use as variable width or precision");
        return 0;
    }
};
// specialization for converttoint when conversion is possible
template<typename t>
struct converttoint<t,true>
{
    static int invoke(const t& value) { return static_cast<int>(value); }
};

} // namespace detail


//------------------------------------------------------------------------------
// variable formatting functions.  may be overridden for user-defined types if
// desired.


// format a value into a stream. called from format() for all types by default.
//
// users may override this for their own types.  when this function is called,
// the stream flags will have been modified according to the format string.
// the format specification is provided in the range [fmtbegin, fmtend).
//
// by default, formatvalue() uses the usual stream insertion operator
// operator<< to format the type t, with special cases for the %c and %p
// conversions.
template<typename t>
inline void formatvalue(std::ostream& out, const char* /*fmtbegin*/,
                        const char* fmtend, const t& value)
{
#ifndef tinyformat_allow_wchar_strings
    // since we don't support printing of wchar_t using "%ls", make it fail at
    // compile time in preference to printing as a void* at runtime.
    typedef typename detail::is_wchar<t>::tinyformat_wchar_is_not_supported dummytype;
    (void) dummytype(); // avoid unused type warning with gcc-4.8
#endif
    // the mess here is to support the %c and %p conversions: if these
    // conversions are active we try to convert the type to a char or const
    // void* respectively and format that instead of the value itself.  for the
    // %p conversion it's important to avoid dereferencing the pointer, which
    // could otherwise lead to a crash when printing a dangling (const char*).
    const bool canconverttochar = detail::is_convertible<t,char>::value;
    const bool canconverttovoidptr = detail::is_convertible<t, const void*>::value;
    if(canconverttochar && *(fmtend-1) == 'c')
        detail::formatvalueastype<t, char>::invoke(out, value);
    else if(canconverttovoidptr && *(fmtend-1) == 'p')
        detail::formatvalueastype<t, const void*>::invoke(out, value);
#ifdef tinyformat_old_libstdcplusplus_workaround
    else if(detail::formatzerointegerworkaround<t>::invoke(out, value)) /**/;
#endif
    else
        out << value;
}


// overloaded version for char types to support printing as an integer
#define tinyformat_define_formatvalue_char(chartype)                  \
inline void formatvalue(std::ostream& out, const char* /*fmtbegin*/,  \
                        const char* fmtend, chartype value)           \
{                                                                     \
    switch(*(fmtend-1))                                               \
    {                                                                 \
        case 'u': case 'd': case 'i': case 'o': case 'x': case 'x':   \
            out << static_cast<int>(value); break;                    \
        default:                                                      \
            out << value;                   break;                    \
    }                                                                 \
}
// per 3.9.1: char, signed char and unsigned char are all distinct types
tinyformat_define_formatvalue_char(char)
tinyformat_define_formatvalue_char(signed char)
tinyformat_define_formatvalue_char(unsigned char)
#undef tinyformat_define_formatvalue_char


//------------------------------------------------------------------------------
// tools for emulating variadic templates in c++98.  the basic idea here is
// stolen from the boost preprocessor metaprogramming library and cut down to
// be just general enough for what we need.

#define tinyformat_argtypes(n) tinyformat_argtypes_ ## n
#define tinyformat_varargs(n) tinyformat_varargs_ ## n
#define tinyformat_passargs(n) tinyformat_passargs_ ## n
#define tinyformat_passargs_tail(n) tinyformat_passargs_tail_ ## n

// to keep it as transparent as possible, the macros below have been generated
// using python via the excellent cog.py code generation script.  this avoids
// the need for a bunch of complex (but more general) preprocessor tricks as
// used in boost.preprocessor.
//
// to rerun the code generation in place, use `cog.py -r tinyformat.h`
// (see http://nedbatchelder.com/code/cog).  alternatively you can just create
// extra versions by hand.

/*[[[cog
maxparams = 16

def makecommaseplists(linetemplate, elemtemplate, startind=1):
    for j in range(startind,maxparams+1):
        list = ', '.join([elemtemplate % {'i':i} for i in range(startind,j+1)])
        cog.outl(linetemplate % {'j':j, 'list':list})

makecommaseplists('#define tinyformat_argtypes_%(j)d %(list)s',
                  'class t%(i)d')

cog.outl()
makecommaseplists('#define tinyformat_varargs_%(j)d %(list)s',
                  'const t%(i)d& v%(i)d')

cog.outl()
makecommaseplists('#define tinyformat_passargs_%(j)d %(list)s', 'v%(i)d')

cog.outl()
cog.outl('#define tinyformat_passargs_tail_1')
makecommaseplists('#define tinyformat_passargs_tail_%(j)d , %(list)s',
                  'v%(i)d', startind = 2)

cog.outl()
cog.outl('#define tinyformat_foreach_argnum(m) \\\n    ' +
         ' '.join(['m(%d)' % (j,) for j in range(1,maxparams+1)]))
]]]*/
#define tinyformat_argtypes_1 class t1
#define tinyformat_argtypes_2 class t1, class t2
#define tinyformat_argtypes_3 class t1, class t2, class t3
#define tinyformat_argtypes_4 class t1, class t2, class t3, class t4
#define tinyformat_argtypes_5 class t1, class t2, class t3, class t4, class t5
#define tinyformat_argtypes_6 class t1, class t2, class t3, class t4, class t5, class t6
#define tinyformat_argtypes_7 class t1, class t2, class t3, class t4, class t5, class t6, class t7
#define tinyformat_argtypes_8 class t1, class t2, class t3, class t4, class t5, class t6, class t7, class t8
#define tinyformat_argtypes_9 class t1, class t2, class t3, class t4, class t5, class t6, class t7, class t8, class t9
#define tinyformat_argtypes_10 class t1, class t2, class t3, class t4, class t5, class t6, class t7, class t8, class t9, class t10
#define tinyformat_argtypes_11 class t1, class t2, class t3, class t4, class t5, class t6, class t7, class t8, class t9, class t10, class t11
#define tinyformat_argtypes_12 class t1, class t2, class t3, class t4, class t5, class t6, class t7, class t8, class t9, class t10, class t11, class t12
#define tinyformat_argtypes_13 class t1, class t2, class t3, class t4, class t5, class t6, class t7, class t8, class t9, class t10, class t11, class t12, class t13
#define tinyformat_argtypes_14 class t1, class t2, class t3, class t4, class t5, class t6, class t7, class t8, class t9, class t10, class t11, class t12, class t13, class t14
#define tinyformat_argtypes_15 class t1, class t2, class t3, class t4, class t5, class t6, class t7, class t8, class t9, class t10, class t11, class t12, class t13, class t14, class t15
#define tinyformat_argtypes_16 class t1, class t2, class t3, class t4, class t5, class t6, class t7, class t8, class t9, class t10, class t11, class t12, class t13, class t14, class t15, class t16

#define tinyformat_varargs_1 const t1& v1
#define tinyformat_varargs_2 const t1& v1, const t2& v2
#define tinyformat_varargs_3 const t1& v1, const t2& v2, const t3& v3
#define tinyformat_varargs_4 const t1& v1, const t2& v2, const t3& v3, const t4& v4
#define tinyformat_varargs_5 const t1& v1, const t2& v2, const t3& v3, const t4& v4, const t5& v5
#define tinyformat_varargs_6 const t1& v1, const t2& v2, const t3& v3, const t4& v4, const t5& v5, const t6& v6
#define tinyformat_varargs_7 const t1& v1, const t2& v2, const t3& v3, const t4& v4, const t5& v5, const t6& v6, const t7& v7
#define tinyformat_varargs_8 const t1& v1, const t2& v2, const t3& v3, const t4& v4, const t5& v5, const t6& v6, const t7& v7, const t8& v8
#define tinyformat_varargs_9 const t1& v1, const t2& v2, const t3& v3, const t4& v4, const t5& v5, const t6& v6, const t7& v7, const t8& v8, const t9& v9
#define tinyformat_varargs_10 const t1& v1, const t2& v2, const t3& v3, const t4& v4, const t5& v5, const t6& v6, const t7& v7, const t8& v8, const t9& v9, const t10& v10
#define tinyformat_varargs_11 const t1& v1, const t2& v2, const t3& v3, const t4& v4, const t5& v5, const t6& v6, const t7& v7, const t8& v8, const t9& v9, const t10& v10, const t11& v11
#define tinyformat_varargs_12 const t1& v1, const t2& v2, const t3& v3, const t4& v4, const t5& v5, const t6& v6, const t7& v7, const t8& v8, const t9& v9, const t10& v10, const t11& v11, const t12& v12
#define tinyformat_varargs_13 const t1& v1, const t2& v2, const t3& v3, const t4& v4, const t5& v5, const t6& v6, const t7& v7, const t8& v8, const t9& v9, const t10& v10, const t11& v11, const t12& v12, const t13& v13
#define tinyformat_varargs_14 const t1& v1, const t2& v2, const t3& v3, const t4& v4, const t5& v5, const t6& v6, const t7& v7, const t8& v8, const t9& v9, const t10& v10, const t11& v11, const t12& v12, const t13& v13, const t14& v14
#define tinyformat_varargs_15 const t1& v1, const t2& v2, const t3& v3, const t4& v4, const t5& v5, const t6& v6, const t7& v7, const t8& v8, const t9& v9, const t10& v10, const t11& v11, const t12& v12, const t13& v13, const t14& v14, const t15& v15
#define tinyformat_varargs_16 const t1& v1, const t2& v2, const t3& v3, const t4& v4, const t5& v5, const t6& v6, const t7& v7, const t8& v8, const t9& v9, const t10& v10, const t11& v11, const t12& v12, const t13& v13, const t14& v14, const t15& v15, const t16& v16

#define tinyformat_passargs_1 v1
#define tinyformat_passargs_2 v1, v2
#define tinyformat_passargs_3 v1, v2, v3
#define tinyformat_passargs_4 v1, v2, v3, v4
#define tinyformat_passargs_5 v1, v2, v3, v4, v5
#define tinyformat_passargs_6 v1, v2, v3, v4, v5, v6
#define tinyformat_passargs_7 v1, v2, v3, v4, v5, v6, v7
#define tinyformat_passargs_8 v1, v2, v3, v4, v5, v6, v7, v8
#define tinyformat_passargs_9 v1, v2, v3, v4, v5, v6, v7, v8, v9
#define tinyformat_passargs_10 v1, v2, v3, v4, v5, v6, v7, v8, v9, v10
#define tinyformat_passargs_11 v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11
#define tinyformat_passargs_12 v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12
#define tinyformat_passargs_13 v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13
#define tinyformat_passargs_14 v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14
#define tinyformat_passargs_15 v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15
#define tinyformat_passargs_16 v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16

#define tinyformat_passargs_tail_1
#define tinyformat_passargs_tail_2 , v2
#define tinyformat_passargs_tail_3 , v2, v3
#define tinyformat_passargs_tail_4 , v2, v3, v4
#define tinyformat_passargs_tail_5 , v2, v3, v4, v5
#define tinyformat_passargs_tail_6 , v2, v3, v4, v5, v6
#define tinyformat_passargs_tail_7 , v2, v3, v4, v5, v6, v7
#define tinyformat_passargs_tail_8 , v2, v3, v4, v5, v6, v7, v8
#define tinyformat_passargs_tail_9 , v2, v3, v4, v5, v6, v7, v8, v9
#define tinyformat_passargs_tail_10 , v2, v3, v4, v5, v6, v7, v8, v9, v10
#define tinyformat_passargs_tail_11 , v2, v3, v4, v5, v6, v7, v8, v9, v10, v11
#define tinyformat_passargs_tail_12 , v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12
#define tinyformat_passargs_tail_13 , v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13
#define tinyformat_passargs_tail_14 , v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14
#define tinyformat_passargs_tail_15 , v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15
#define tinyformat_passargs_tail_16 , v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16

#define tinyformat_foreach_argnum(m) \
    m(1) m(2) m(3) m(4) m(5) m(6) m(7) m(8) m(9) m(10) m(11) m(12) m(13) m(14) m(15) m(16)
//[[[end]]]



namespace detail {

// class holding current position in format string and an output stream into
// which arguments are formatted.
class formatiterator
{
    public:
        // flags for features not representable with standard stream state
        enum extraformatflags
        {
            flag_none                = 0,
            flag_truncatetoprecision = 1<<0, // truncate length to stream precision()
            flag_spacepadpositive    = 1<<1, // pad positive values with spaces
            flag_variablewidth       = 1<<2, // variable field width in arg list
            flag_variableprecision   = 1<<3  // variable field precision in arg list
        };

        // out is the output stream, fmt is the full format string
        formatiterator(std::ostream& out, const char* fmt)
            : m_out(out),
            m_fmt(fmt),
            m_extraflags(flag_none),
            m_wantwidth(false),
            m_wantprecision(false),
            m_variablewidth(0),
            m_variableprecision(0),
            m_origwidth(out.width()),
            m_origprecision(out.precision()),
            m_origflags(out.flags()),
            m_origfill(out.fill())
        { }

        // print remaining part of format string.
        void finish()
        {
            // it would be nice if we could do this from the destructor, but we
            // can't if tinformat_error is used to throw an exception!
            m_fmt = printformatstringliteral(m_out, m_fmt);
            if(*m_fmt != '\0')
                tinyformat_error("tinyformat: too many conversion specifiers in format string");
        }

        ~formatiterator()
        {
            // restore stream state
            m_out.width(m_origwidth);
            m_out.precision(m_origprecision);
            m_out.flags(m_origflags);
            m_out.fill(m_origfill);
        }

        template<typename t>
        void accept(const t& value);

    private:
        // parse and return an integer from the string c, as atoi()
        // on return, c is set to one past the end of the integer.
        static int parseintandadvance(const char*& c)
        {
            int i = 0;
            for(;*c >= '0' && *c <= '9'; ++c)
                i = 10*i + (*c - '0');
            return i;
        }

        // format at most trunclen characters of a c string to the given
        // stream.  return true if formatting proceeded (generic version always
        // returns false)
        template<typename t>
        static bool formatcstringtruncate(std::ostream& /*out*/, const t& /*value*/,
                                        std::streamsize /*trunclen*/)
        {
            return false;
        }
#       define tinyformat_define_format_c_string_truncate(type)            \
        static bool formatcstringtruncate(std::ostream& out, type* value,  \
                                        std::streamsize trunclen)          \
        {                                                                  \
            std::streamsize len = 0;                                       \
            while(len < trunclen && value[len] != 0)                       \
                ++len;                                                     \
            out.write(value, len);                                         \
            return true;                                                   \
        }
        // overload for const char* and char*.  could overload for signed &
        // unsigned char too, but these are technically unneeded for printf
        // compatibility.
        tinyformat_define_format_c_string_truncate(const char)
        tinyformat_define_format_c_string_truncate(char)
#       undef tinyformat_define_format_c_string_truncate

        // print literal part of format string and return next format spec
        // position.
        //
        // skips over any occurrences of '%%', printing a literal '%' to the
        // output.  the position of the first % character of the next
        // nontrivial format spec is returned, or the end of string.
        static const char* printformatstringliteral(std::ostream& out,
                                                    const char* fmt)
        {
            const char* c = fmt;
            for(; true; ++c)
            {
                switch(*c)
                {
                    case '\0':
                        out.write(fmt, static_cast<std::streamsize>(c - fmt));
                        return c;
                    case '%':
                        out.write(fmt, static_cast<std::streamsize>(c - fmt));
                        if(*(c+1) != '%')
                            return c;
                        // for "%%", tack trailing % onto next literal section.
                        fmt = ++c;
                        break;
                }
            }
        }

        static const char* streamstatefromformat(std::ostream& out,
                                                 unsigned int& extraflags,
                                                 const char* fmtstart,
                                                 int variablewidth,
                                                 int variableprecision);

        // private copy & assign: kill gcc warnings with -weffc++
        formatiterator(const formatiterator&);
        formatiterator& operator=(const formatiterator&);

        // stream, current format string & state
        std::ostream& m_out;
        const char* m_fmt;
        unsigned int m_extraflags;
        // state machine info for handling of variable width & precision
        bool m_wantwidth;
        bool m_wantprecision;
        int m_variablewidth;
        int m_variableprecision;
        // saved stream state
        std::streamsize m_origwidth;
        std::streamsize m_origprecision;
        std::ios::fmtflags m_origflags;
        char m_origfill;
};


// accept a value for formatting into the internal stream.
template<typename t>
tinyformat_noinline  // < greatly reduces bloat in optimized builds
void formatiterator::accept(const t& value)
{
    // parse the format string
    const char* fmtend = 0;
    if(m_extraflags == flag_none && !m_wantwidth && !m_wantprecision)
    {
        m_fmt = printformatstringliteral(m_out, m_fmt);
        fmtend = streamstatefromformat(m_out, m_extraflags, m_fmt, 0, 0);
        m_wantwidth     = (m_extraflags & flag_variablewidth) != 0;
        m_wantprecision = (m_extraflags & flag_variableprecision) != 0;
    }
    // consume value as variable width and precision specifier if necessary
    if(m_extraflags & (flag_variablewidth | flag_variableprecision))
    {
        if(m_wantwidth || m_wantprecision)
        {
            int v = converttoint<t>::invoke(value);
            if(m_wantwidth)
            {
                m_variablewidth = v;
                m_wantwidth = false;
            }
            else if(m_wantprecision)
            {
                m_variableprecision = v;
                m_wantprecision = false;
            }
            return;
        }
        // if we get here, we've set both the variable precision and width as
        // required and we need to rerun the stream state setup to insert these.
        fmtend = streamstatefromformat(m_out, m_extraflags, m_fmt,
                                       m_variablewidth, m_variableprecision);
    }

    // format the value into the stream.
    if(!(m_extraflags & (flag_spacepadpositive | flag_truncatetoprecision)))
        formatvalue(m_out, m_fmt, fmtend, value);
    else
    {
        // the following are special cases where there's no direct
        // correspondence between stream formatting and the printf() behaviour.
        // instead, we simulate the behaviour crudely by formatting into a
        // temporary string stream and munging the resulting string.
        std::ostringstream tmpstream;
        tmpstream.copyfmt(m_out);
        if(m_extraflags & flag_spacepadpositive)
            tmpstream.setf(std::ios::showpos);
        // formatcstringtruncate is required for truncating conversions like
        // "%.4s" where at most 4 characters of the c-string should be read.
        // if we didn't include this special case, we might read off the end.
        if(!( (m_extraflags & flag_truncatetoprecision) &&
             formatcstringtruncate(tmpstream, value, m_out.precision()) ))
        {
            // not a truncated c-string; just format normally.
            formatvalue(tmpstream, m_fmt, fmtend, value);
        }
        std::string result = tmpstream.str(); // allocates... yuck.
        if(m_extraflags & flag_spacepadpositive)
        {
            for(size_t i = 0, iend = result.size(); i < iend; ++i)
                if(result[i] == '+')
                    result[i] = ' ';
        }
        if((m_extraflags & flag_truncatetoprecision) &&
           (int)result.size() > (int)m_out.precision())
            m_out.write(result.c_str(), m_out.precision());
        else
            m_out << result;
    }
    m_extraflags = flag_none;
    m_fmt = fmtend;
}


// parse a format string and set the stream state accordingly.
//
// the format mini-language recognized here is meant to be the one from c99,
// with the form "%[flags][width][.precision][length]type".
//
// formatting options which can't be natively represented using the ostream
// state are returned in the extraflags parameter which is a bitwise
// combination of values from the extraformatflags enum.
inline const char* formatiterator::streamstatefromformat(std::ostream& out,
                                                         unsigned int& extraflags,
                                                         const char* fmtstart,
                                                         int variablewidth,
                                                         int variableprecision)
{
    if(*fmtstart != '%')
    {
        tinyformat_error("tinyformat: not enough conversion specifiers in format string");
        return fmtstart;
    }
    // reset stream state to defaults.
    out.width(0);
    out.precision(6);
    out.fill(' ');
    // reset most flags; ignore irrelevant unitbuf & skipws.
    out.unsetf(std::ios::adjustfield | std::ios::basefield |
               std::ios::floatfield | std::ios::showbase | std::ios::boolalpha |
               std::ios::showpoint | std::ios::showpos | std::ios::uppercase);
    extraflags = flag_none;
    bool precisionset = false;
    bool widthset = false;
    const char* c = fmtstart + 1;
    // 1) parse flags
    for(;; ++c)
    {
        switch(*c)
        {
            case '#':
                out.setf(std::ios::showpoint | std::ios::showbase);
                continue;
            case '0':
                // overridden by left alignment ('-' flag)
                if(!(out.flags() & std::ios::left))
                {
                    // use internal padding so that numeric values are
                    // formatted correctly, eg -00010 rather than 000-10
                    out.fill('0');
                    out.setf(std::ios::internal, std::ios::adjustfield);
                }
                continue;
            case '-':
                out.fill(' ');
                out.setf(std::ios::left, std::ios::adjustfield);
                continue;
            case ' ':
                // overridden by show positive sign, '+' flag.
                if(!(out.flags() & std::ios::showpos))
                    extraflags |= flag_spacepadpositive;
                continue;
            case '+':
                out.setf(std::ios::showpos);
                extraflags &= ~flag_spacepadpositive;
                continue;
        }
        break;
    }
    // 2) parse width
    if(*c >= '0' && *c <= '9')
    {
        widthset = true;
        out.width(parseintandadvance(c));
    }
    if(*c == '*')
    {
        widthset = true;
        if(variablewidth < 0)
        {
            // negative widths correspond to '-' flag set
            out.fill(' ');
            out.setf(std::ios::left, std::ios::adjustfield);
            variablewidth = -variablewidth;
        }
        out.width(variablewidth);
        extraflags |= flag_variablewidth;
        ++c;
    }
    // 3) parse precision
    if(*c == '.')
    {
        ++c;
        int precision = 0;
        if(*c == '*')
        {
            ++c;
            extraflags |= flag_variableprecision;
            precision = variableprecision;
        }
        else
        {
            if(*c >= '0' && *c <= '9')
                precision = parseintandadvance(c);
            else if(*c == '-') // negative precisions ignored, treated as zero.
                parseintandadvance(++c);
        }
        out.precision(precision);
        precisionset = true;
    }
    // 4) ignore any c99 length modifier
    while(*c == 'l' || *c == 'h' || *c == 'l' ||
          *c == 'j' || *c == 'z' || *c == 't')
        ++c;
    // 5) we're up to the conversion specifier character.
    // set stream flags based on conversion specifier (thanks to the
    // boost::format class for forging the way here).
    bool intconversion = false;
    switch(*c)
    {
        case 'u': case 'd': case 'i':
            out.setf(std::ios::dec, std::ios::basefield);
            intconversion = true;
            break;
        case 'o':
            out.setf(std::ios::oct, std::ios::basefield);
            intconversion = true;
            break;
        case 'x':
            out.setf(std::ios::uppercase);
        case 'x': case 'p':
            out.setf(std::ios::hex, std::ios::basefield);
            intconversion = true;
            break;
        case 'e':
            out.setf(std::ios::uppercase);
        case 'e':
            out.setf(std::ios::scientific, std::ios::floatfield);
            out.setf(std::ios::dec, std::ios::basefield);
            break;
        case 'f':
            out.setf(std::ios::uppercase);
        case 'f':
            out.setf(std::ios::fixed, std::ios::floatfield);
            break;
        case 'g':
            out.setf(std::ios::uppercase);
        case 'g':
            out.setf(std::ios::dec, std::ios::basefield);
            // as in boost::format, let stream decide float format.
            out.flags(out.flags() & ~std::ios::floatfield);
            break;
        case 'a': case 'a':
            tinyformat_error("tinyformat: the %a and %a conversion specs "
                             "are not supported");
            break;
        case 'c':
            // handled as special case inside formatvalue()
            break;
        case 's':
            if(precisionset)
                extraflags |= flag_truncatetoprecision;
            // make %s print booleans as "true" and "false"
            out.setf(std::ios::boolalpha);
            break;
        case 'n':
            // not supported - will cause problems!
            tinyformat_error("tinyformat: %n conversion spec not supported");
            break;
        case '\0':
            tinyformat_error("tinyformat: conversion spec incorrectly "
                             "terminated by end of string");
            return c;
    }
    if(intconversion && precisionset && !widthset)
    {
        // "precision" for integers gives the minimum number of digits (to be
        // padded with zeros on the left).  this isn't really supported by the
        // iostreams, but we can approximately simulate it with the width if
        // the width isn't otherwise used.
        out.width(out.precision());
        out.setf(std::ios::internal, std::ios::adjustfield);
        out.fill('0');
    }
    return c+1;
}



//------------------------------------------------------------------------------
// private format function on top of which the public interface is implemented.
// we enforce a mimimum of one value to be formatted to prevent bugs looking like
//
//   const char* mystr = "100% broken";
//   printf(mystr);   // parses % as a format specifier
#ifdef tinyformat_use_variadic_templates

template<typename t1>
void format(formatiterator& fmtiter, const t1& value1)
{
    fmtiter.accept(value1);
    fmtiter.finish();
}

// general version for c++11
template<typename t1, typename... args>
void format(formatiterator& fmtiter, const t1& value1, const args&... args)
{
    fmtiter.accept(value1);
    format(fmtiter, args...);
}

#else

inline void format(formatiterator& fmtiter)
{
    fmtiter.finish();
}

// general version for c++98
#define tinyformat_make_format_detail(n)                                  \
template<tinyformat_argtypes(n)>                                          \
void format(detail::formatiterator& fmtiter, tinyformat_varargs(n))       \
{                                                                         \
    fmtiter.accept(v1);                                                   \
    format(fmtiter tinyformat_passargs_tail(n));                          \
}

tinyformat_foreach_argnum(tinyformat_make_format_detail)
#undef tinyformat_make_format_detail

#endif // end c++98 variadic template emulation for format()

} // namespace detail


//------------------------------------------------------------------------------
// implement all the main interface functions here in terms of detail::format()

#ifdef tinyformat_use_variadic_templates

// c++11 - the simple case
template<typename t1, typename... args>
void format(std::ostream& out, const char* fmt, const t1& v1, const args&... args)
{
    detail::formatiterator fmtiter(out, fmt);
    format(fmtiter, v1, args...);
}

template<typename t1, typename... args>
std::string format(const char* fmt, const t1& v1, const args&... args)
{
    std::ostringstream oss;
    format(oss, fmt, v1, args...);
    return oss.str();
}

template<typename t1, typename... args>
std::string format(const std::string &fmt, const t1& v1, const args&... args)
{
    std::ostringstream oss;
    format(oss, fmt.c_str(), v1, args...);
    return oss.str();
}

template<typename t1, typename... args>
void printf(const char* fmt, const t1& v1, const args&... args)
{
    format(std::cout, fmt, v1, args...);
}

#else

// c++98 - define the interface functions using the wrapping macros
#define tinyformat_make_format_funcs(n)                                   \
                                                                          \
template<tinyformat_argtypes(n)>                                          \
void format(std::ostream& out, const char* fmt, tinyformat_varargs(n))    \
{                                                                         \
    tinyformat::detail::formatiterator fmtiter(out, fmt);                 \
    tinyformat::detail::format(fmtiter, tinyformat_passargs(n));          \
}                                                                         \
                                                                          \
template<tinyformat_argtypes(n)>                                          \
std::string format(const char* fmt, tinyformat_varargs(n))                \
{                                                                         \
    std::ostringstream oss;                                               \
    tinyformat::format(oss, fmt, tinyformat_passargs(n));                 \
    return oss.str();                                                     \
}                                                                         \
                                                                          \
template<tinyformat_argtypes(n)>                                          \
std::string format(const std::string &fmt, tinyformat_varargs(n))         \
{                                                                         \
    std::ostringstream oss;                                               \
    tinyformat::format(oss, fmt.c_str(), tinyformat_passargs(n));         \
    return oss.str();                                                     \
}                                                                         \
                                                                          \
template<tinyformat_argtypes(n)>                                          \
void printf(const char* fmt, tinyformat_varargs(n))                       \
{                                                                         \
    tinyformat::format(std::cout, fmt, tinyformat_passargs(n));           \
}

tinyformat_foreach_argnum(tinyformat_make_format_funcs)
#undef tinyformat_make_format_funcs
#endif


//------------------------------------------------------------------------------
// define deprecated wrapping macro for backward compatibility in tinyformat
// 1.x.  will be removed in version 2!
#define tinyformat_wrap_format_extra_args
#define tinyformat_wrap_format_n(n, returntype, funcname, funcdeclsuffix,  \
                                 bodyprefix, streamname, bodysuffix)       \
template<tinyformat_argtypes(n)>                                           \
returntype funcname(tinyformat_wrap_format_extra_args const char* fmt,     \
                    tinyformat_varargs(n)) funcdeclsuffix                  \
{                                                                          \
    bodyprefix                                                             \
    tinyformat::format(streamname, fmt, tinyformat_passargs(n));           \
    bodysuffix                                                             \
}                                                                          \

#define tinyformat_wrap_format(returntype, funcname, funcdeclsuffix,       \
                               bodyprefix, streamname, bodysuffix)         \
inline                                                                     \
returntype funcname(tinyformat_wrap_format_extra_args const char* fmt      \
                    ) funcdeclsuffix                                       \
{                                                                          \
    bodyprefix                                                             \
    tinyformat::detail::formatiterator(streamname, fmt).finish();          \
    bodysuffix                                                             \
}                                                                          \
tinyformat_wrap_format_n(1 , returntype, funcname, funcdeclsuffix, bodyprefix, streamname, bodysuffix) \
tinyformat_wrap_format_n(2 , returntype, funcname, funcdeclsuffix, bodyprefix, streamname, bodysuffix) \
tinyformat_wrap_format_n(3 , returntype, funcname, funcdeclsuffix, bodyprefix, streamname, bodysuffix) \
tinyformat_wrap_format_n(4 , returntype, funcname, funcdeclsuffix, bodyprefix, streamname, bodysuffix) \
tinyformat_wrap_format_n(5 , returntype, funcname, funcdeclsuffix, bodyprefix, streamname, bodysuffix) \
tinyformat_wrap_format_n(6 , returntype, funcname, funcdeclsuffix, bodyprefix, streamname, bodysuffix) \
tinyformat_wrap_format_n(7 , returntype, funcname, funcdeclsuffix, bodyprefix, streamname, bodysuffix) \
tinyformat_wrap_format_n(8 , returntype, funcname, funcdeclsuffix, bodyprefix, streamname, bodysuffix) \
tinyformat_wrap_format_n(9 , returntype, funcname, funcdeclsuffix, bodyprefix, streamname, bodysuffix) \
tinyformat_wrap_format_n(10, returntype, funcname, funcdeclsuffix, bodyprefix, streamname, bodysuffix) \
tinyformat_wrap_format_n(11, returntype, funcname, funcdeclsuffix, bodyprefix, streamname, bodysuffix) \
tinyformat_wrap_format_n(12, returntype, funcname, funcdeclsuffix, bodyprefix, streamname, bodysuffix) \
tinyformat_wrap_format_n(13, returntype, funcname, funcdeclsuffix, bodyprefix, streamname, bodysuffix) \
tinyformat_wrap_format_n(14, returntype, funcname, funcdeclsuffix, bodyprefix, streamname, bodysuffix) \
tinyformat_wrap_format_n(15, returntype, funcname, funcdeclsuffix, bodyprefix, streamname, bodysuffix) \
tinyformat_wrap_format_n(16, returntype, funcname, funcdeclsuffix, bodyprefix, streamname, bodysuffix) \


} // namespace tinyformat

#define strprintf tfm::format

#endif // tinyformat_h_included
