#!/bin/bash

# this is a thin wrapper around moorecoin-cli that strips the windows-style eols
# from the output if present. it is necessary when using moorecoin-cli.exe on
# linux since shells will interpret the line-endings as part of the result.

curdir=$(cd $(dirname "$0"); pwd)
# get builddir and real_moorecoind

# grab the value of $real_moorecoincli which may be moorecoin-cli.exe.
. "${curdir}/tests-config.sh"

"${real_moorecoincli}" "$@" | sed 's/\r//'
